[package]
name = "hash_str"
version = "0.0.1"
edition = "2021"

[dependencies]
ahash = "0.8.11"
bumpalo = { version = "3.17.0", optional = true }
hashbrown = { version = "0.15.2", optional = true }

[features]
default = []
cache = ["dep:bumpalo","dep:hashbrown"]
